/**
 * Turn a fuzz failure or a browser duel journal, at answer N, into a Layer 1 scenario file.
 *
 *   npx tsx scripts/failure-to-scenario.ts --file tests/fuzz/failures/<case>.json --step 120
 *   npx tsx scripts/failure-to-scenario.ts --file duel-journal-<slug>.json --step 37 --out tests/scenarios/generated/my-case.ts --name my-case
 *
 * --file  a fuzz failure JSON (scripts/fuzz-repro.ts format) or a journal (scripts/replay-journal.ts format)
 * --step  replay this many answers, then capture the board (default for a fuzz failure: the step it failed at)
 * --out   default tests/scenarios/generated/<name>.ts
 * --wasm  replay on this core (default: the core recorded in a differential file, else the data directory's)
 * --name  scenario id (kebab-case). Default: derived from the file name and step.
 *
 * Needs the engine data of the run (DUEL_DATA_DIR, default data/duel-engine-next). See tests/scenarios/generated/README.md.
 */
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { engineDataDirectory } from "../tests/fuzz/config.js";
import { describeCard } from "../tests/support/card-catalog.js";
import { captureBoard, renderPresetDraft, renderScenario, type Capture, type CardLookup } from "./lib/board-capture.js";
import { loadSource, replaySource, type DuelSource } from "./lib/replay-source.js";
import { createEngineGame, eliminationCodeOf } from "../src/engine.js";
import { engineSeed } from "../tests/fuzz/rng.js";
import { savedFuzzFirstTurnDraw } from "./lib/fuzz-draw-rule.js";
import { isDuelFormat, legacyDuelSettings, normalizeDuelSettings, seatCountFor, type DuelDeck, type DuelEngineView, type DuelFormat } from "@yugidraft/shared/duels";

const PACKAGE_DIR = resolve(dirname(fileURLToPath(import.meta.url)), "..");

export function catalogLookup(dataDirectory: string): CardLookup {
  return {
    describe(code) {
      try {
        const card = describeCard(code, dataDirectory);
        let unique = false;
        try {
          unique = describeCard(card.name, dataDirectory).code === code;
        } catch {
          unique = false;
        }
        return { name: card.name, unique };
      } catch {
        return null;
      }
    },
  };
}

export function slugify(text: string): string {
  return text.toLowerCase().replace(/\.json$/, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

export async function generate(options: { file: string; step?: number; name?: string; dataDirectory?: string; wasmPath?: string }) {
  const dataDirectory = options.dataDirectory ?? engineDataDirectory();
  const source = loadSource(options.file);
  const step = options.step ?? source.failureStep;
  if (step === undefined) throw new Error("Give --step N (the source has no failure step)");
  const views = await replaySource(source, dataDirectory, step, undefined, options.wasmPath ? { wasmPath: options.wasmPath } : {});
  const capture = captureBoard(
    { seats: views.seats, spectator: views.spectator, mode: source.mode, masterRule: source.masterRule, decks: source.decks },
    catalogLookup(dataDirectory),
  );
  const name = options.name ?? `${slugify(basename(options.file))}-step-${step}`;
  const relPath = relative(resolve(PACKAGE_DIR, "../.."), resolve(options.file));
  const shown = relPath.startsWith("..") ? resolve(options.file) : relPath;
  const { summary } = capture;
  const text = renderScenario({
    id: name,
    title: `Board of ${source.label} after answer ${step}`,
    source: `generated from ${shown} at answer ${step}; replace with the ruling URL once the expected result is written`,
    header: [
      `Generated by scripts/failure-to-scenario.ts. Do not trust the expected result: write it by hand.`,
      `Source: ${shown} (${source.kind}), answer ${step} of ${source.commands.length}, ${source.label}`,
      `Captured: turn ${summary.turn}, phase ${summary.phase}, turn player seat ${summary.turnSeat}${summary.prompt ? `, open prompt: ${summary.prompt}` : ""}`,
      `Engine data: ${dataDirectory}`,
    ],
    warnings: capture.warnings,
    capture,
  });
  return { name, text, capture, source, step };
}

// ---------- 3 and 4 seats ----------

/** A duel source with its table format, seat count and the core identity the file records. */
export interface NSource extends DuelSource {
  format: DuelFormat;
  seatCount: number;
  /** sha256 of the wasm the run used (journal `wasmSha`, fuzz-n `wasm.sha256`). */
  wasmSha?: string;
}

function startupScriptsOf(value: unknown): Array<{ name: string; content: string }> | undefined {
  if (!Array.isArray(value) || value.length === 0) return undefined;
  return value.map((item, index) => (typeof item === "string" ? { name: `startup-${index}.lua`, content: item } : (item as { name: string; content: string })));
}

function formatOf(raw: unknown, deckCount: number): DuelFormat {
  if (isDuelFormat(raw)) return raw;
  return deckCount === 3 ? "ffa3" : deckCount >= 4 ? "ffa4" : "1v1";
}

/** Read any input that holds a duel: the `loadSource` types, plus a fuzz-n failure file (`answers`, `check`, `wasm`). */
export function loadNSource(file: string): NSource {
  const raw = JSON.parse(readFileSync(file, "utf8")) as Record<string, any>;
  if (Array.isArray(raw.answers) && raw.check && raw.scenario && Array.isArray(raw.decks)) {
    const scenario = raw.scenario as { seed: number; mode: NSource["mode"]; masterRule: NSource["masterRule"]; format: DuelFormat };
    const format = formatOf(scenario.format ?? raw.format, raw.decks.length);
    const commands = (raw.answers as Array<Record<string, any>>).map((item) =>
      item.kind === "eliminate"
        ? { seat: item.seat as number, promptId: `eliminate:${item.reason}`, revision: item.revision as number, answer: {} as never }
        : { seat: item.seat as number, promptId: item.promptId as string, revision: item.revision as number, answer: item.answer },
    );
    return {
      kind: "fuzz",
      label: `fuzz-n ${format} seed ${scenario.seed} core ${raw.wasm?.tag ?? "?"}`,
      mode: scenario.mode,
      masterRule: scenario.masterRule,
      firstTurnDraw: savedFuzzFirstTurnDraw(raw.engine?.firstTurnDraw, scenario.mode, scenario.masterRule),
      decks: raw.decks,
      seed: engineSeed(scenario.seed),
      commands,
      ...(raw.check?.step !== undefined ? { failureStep: raw.check.step as number } : {}),
      ...(raw.wasm?.sha256 ? { wasmSha: raw.wasm.sha256 as string } : {}),
      ...(raw.wasm?.path ? { wasmPath: raw.wasm.path as string } : {}),
      format,
      seatCount: seatCountFor(format),
    };
  }
  const base = loadSource(file);
  const format = base.format ?? formatOf(raw.tableFormat ?? raw.format, base.decks.length);
  const scripts = base.startupScripts ?? startupScriptsOf(raw.startupScripts);
  const wasmSha = typeof raw.wasmSha === "string" ? raw.wasmSha : typeof raw.differential?.multiWasmSha === "string" ? raw.differential.multiWasmSha : undefined;
  return { ...base, format, seatCount: seatCountFor(format), ...(scripts ? { startupScripts: scripts } : {}), ...(wasmSha ? { wasmSha } : {}) };
}

function sha256File(path: string): string {
  return createHash("sha256").update(readFileSync(path)).digest("hex");
}

/** Wasm files that may hold a core: the data directory, the dist builds, and `DUEL_WASM_DIRS` (path list). */
export function candidateWasmFiles(dataDirectory: string): string[] {
  const dirs = [dataDirectory, resolve(PACKAGE_DIR, "domain-core/dist"), ...(process.env.DUEL_WASM_DIRS ?? "").split(":").filter(Boolean)];
  const files: string[] = [];
  for (const dir of dirs) {
    if (!existsSync(dir)) continue;
    for (const name of readdirSync(dir)) if (name.endsWith(".wasm")) files.push(resolve(dir, name));
  }
  return files;
}

/** The wasm whose sha256 equals `sha` (a full hash, or a prefix of 8 or more hex digits). */
export function findWasmBySha(sha: string, files: string[]): string | undefined {
  const want = sha.toLowerCase();
  if (want.length < 8) return undefined;
  for (const file of files) {
    const have = sha256File(file);
    if (have.startsWith(want) || want.startsWith(have)) return file;
  }
  return undefined;
}

export interface ChosenCore {
  /** The wasm to replay on. Undefined = the engine default of the data directory. */
  path?: string;
  warnings: string[];
}

/**
 * Pick the core for a replay. Order: an explicit path; the wasm whose sha matches the file's `wasmSha`; the wasm path the file
 * names (when it exists here); for 3 or 4 seats the data directory multi core, with a warning.
 */
export function chooseCore(source: NSource, dataDirectory: string, explicit?: string): ChosenCore {
  const warnings: string[] = [];
  if (explicit) return { path: resolve(explicit), warnings };
  if (source.wasmSha) {
    const hit = findWasmBySha(source.wasmSha, candidateWasmFiles(dataDirectory));
    if (hit) return { path: hit, warnings };
    warnings.push(`No wasm with sha ${source.wasmSha.slice(0, 12)} was found (looked in the data directory, domain-core/dist and DUEL_WASM_DIRS).`);
  } else if (source.seatCount > 2) {
    warnings.push("The journal has no wasmSha (it was written before journals recorded the core).");
  }
  for (const candidate of [source.wasmPath && resolve(source.wasmPath), source.wasmPath && resolve(PACKAGE_DIR, source.wasmPath)]) {
    if (candidate && existsSync(candidate)) return { path: candidate, warnings };
  }
  if (source.seatCount > 2) {
    const multi = resolve(dataDirectory, source.mode === "domain" ? "ocgcore.multi-domain.wasm" : "ocgcore.multi.wasm");
    warnings.push(`Falling back to ${multi}. The board may differ from the recorded run.`);
  }
  return { warnings };
}

export interface NReplay {
  step: number;
  /** One view per seat, each read as that seat. */
  seats: DuelEngineView[];
  spectator: DuelEngineView;
}

/** Replay `step` answers of a source with any seat count and read every seat. A replay error carries the answer index. */
export async function replaySeats(source: NSource, dataDirectory: string, step: number, wasmPath?: string): Promise<NReplay> {
  if (step < 0 || step > source.commands.length) throw new Error(`--step ${step} is outside 0..${source.commands.length} (the source has ${source.commands.length} answers)`);
  let wasm: ArrayBuffer | undefined;
  if (wasmPath) {
    if (!existsSync(wasmPath)) throw new Error(`The wasm file ${wasmPath} does not exist`);
    const bytes = readFileSync(wasmPath);
    wasm = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer;
  }
  const game = await createEngineGame({
    mode: source.mode,
    masterRule: source.masterRule,
    decks: source.decks as DuelDeck[],
    seed: source.seed,
    dataDirectory,
    ...(source.firstTurnDraw !== undefined ? { firstTurnDraw: source.firstTurnDraw } : {}),
    settings: source.settings ?? (source.kind === "journal" ? legacyDuelSettings() : normalizeDuelSettings(source.mode, undefined)),
    ...(source.startupScripts ? { startupScripts: source.startupScripts } : {}),
    ...(source.format !== "1v1" ? { format: source.format } : {}),
    ...(wasm ? (source.seatCount > 2 ? { multiWasmBinary: wasm } : { standardWasmBinary: wasm }) : {}),
  });
  try {
    for (let done = 0; done < step; done++) {
      const command = source.commands[done]!;
      const view = game.view(command.seat);
      const elimination = eliminationCodeOf(command.promptId);
      if (view.revision !== command.revision || (elimination === null && view.prompt?.id !== command.promptId)) {
        throw new Error(
          `answer ${done}: the journal has revision ${command.revision} prompt ${command.promptId}; the engine has revision ${view.revision} prompt ${view.prompt?.id ?? "none"}. The replay does not match the recorded run. Check the saved options and engine resources.`,
        );
      }
      if (elimination === null) game.answer(command.seat, command.promptId, command.answer);
      else game.eliminate(command.seat, elimination);
    }
    return { step, seats: Array.from({ length: source.seatCount }, (_, seat) => game.view(seat)), spectator: game.view(null) };
  } finally {
    game.close();
  }
}

export interface DraftResult {
  name: string;
  text: string;
  capture: Capture;
  source: NSource;
  step: number;
  core: ChosenCore;
}

/** Replay a 3 or 4 seat duel, capture every seat at `step` (default: the failure step, else the end) and render a preset draft. */
export async function generateDraft(options: { file: string; step?: number; name?: string; dataDirectory?: string; wasmPath?: string; title?: string }): Promise<DraftResult> {
  const dataDirectory = options.dataDirectory ?? engineDataDirectory();
  const source = loadNSource(options.file);
  const core = chooseCore(source, dataDirectory, options.wasmPath);
  let step = options.step ?? source.failureStep;
  if (step === undefined || step < 0 || step > source.commands.length) step = source.commands.length;
  const replay = await replaySeats(source, dataDirectory, step, core.path);
  const capture = captureBoard(
    { seats: replay.seats, spectator: replay.spectator, format: source.format, mode: source.mode, masterRule: source.masterRule, decks: source.decks },
    catalogLookup(dataDirectory),
  );
  const name = options.name ?? `${slugify(basename(options.file))}-step-${step}`;
  const relPath = relative(resolve(PACKAGE_DIR, "../.."), resolve(options.file));
  const shown = relPath.startsWith("..") ? resolve(options.file) : relPath;
  const { summary } = capture;
  const warnings = [...core.warnings, ...capture.warnings];
  if (replay.seats[0]?.result) warnings.unshift("The duel had ended at this step (a result is set). The draft is the board at the end.");
  const text = renderPresetDraft({
    id: name,
    title: options.title ?? `Draft of ${source.label} after answer ${step}`,
    header: [
      `Generated by scripts/triage.ts (scripts/failure-to-scenario.ts generateDraft). Do not trust it: write the bot rules and the checklist by hand.`,
      `Source: ${shown} (${source.kind}), answer ${step} of ${source.commands.length}, ${source.label}, ${source.format}`,
      `Captured: turn ${summary.turn}, phase ${summary.phase}, turn player seat ${summary.turnSeat}${summary.prompt ? `, open prompt: ${summary.prompt}` : ""}`,
      `Core: ${core.path ?? `${dataDirectory} (data directory)`}${source.wasmSha ? ` (journal sha ${source.wasmSha.slice(0, 12)})` : ""}`,
    ],
    warnings,
    capture,
  });
  return { name, text, capture, source, step, core };
}

function arg(name: string): string | undefined {
  const index = process.argv.indexOf(`--${name}`);
  return index >= 0 ? process.argv[index + 1] : undefined;
}

async function main(): Promise<void> {
  const file = arg("file");
  if (!file) throw new Error("Usage: failure-to-scenario.ts --file <fuzz failure | duel journal>.json --step N [--out path] [--name id]");
  const stepArg = arg("step");
  const result = await generate({ file, step: stepArg === undefined ? undefined : Number(stepArg), name: arg("name"), wasmPath: arg("wasm") });
  const out = resolve(arg("out") ?? resolve(PACKAGE_DIR, "tests/scenarios/generated", `${result.name}.ts`));
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, result.text);
  console.log(`wrote ${out}`);
  console.log(`${result.capture.warnings.length} warning(s):`);
  for (const warning of result.capture.warnings) console.log(`  - ${warning}`);
  console.log(`run: SCENARIO_ID=${result.name} DUEL_DATA_DIR=${engineDataDirectory()} npx vitest run tests/scenarios/generated`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  });
}
