// Rule coverage table for ADR-0002 (multi-player duel rules).
// Reads the rule ids from the ADR, collects the `rules: [...]` declared by tests, and writes
// docs/specs/multiplayer-rule-coverage.md. Exit code is 0, unless --strict is given and a rule has no covering test.
// Usage: npx tsx scripts/rule-coverage.ts [--strict] [--check]   (--check: print only, write nothing)

import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

export type Status = "covered" | "pending only" | "none";
export interface RuleRef {
  /** Test id: a catalog id, or the file path for a real test. */
  test: string;
  /** True for a catalog entry that is still a sketch. */
  pending: boolean;
}
export interface RuleRow {
  id: string;
  title: string;
  status: Status;
  tests: RuleRef[];
}

const ID = "R-(?:COMMON|TAG|FFA)-[A-Z0-9]+(?:-[A-Z0-9]+)*";

/** Parse the rule ids from the ADR. A rule bullet starts with "- `[R-...]`". */
export function parseAdrRules(markdown: string): { id: string; title: string }[] {
  const rules: { id: string; title: string }[] = [];
  const pattern = new RegExp("^- `\\[(" + ID + ")\\]` (.*)$", "gm");
  for (const match of markdown.matchAll(pattern)) {
    const title = match[2]!
      .replace(/\*\*/g, "")
      .replace(/\s+/g, " ")
      .trim();
    rules.push({ id: match[1]!, title: title.length > 90 ? `${title.slice(0, 87).trimEnd()}...` : title });
  }
  return rules;
}

/** Find the ids in every `rules: [ ... ]` array of a source text. */
export function parseRuleDeclarations(source: string): string[] {
  const found = new Set<string>();
  for (const block of source.matchAll(/\brules\s*:\s*\[([^\]]*)\]/g)) {
    for (const id of block[1]!.matchAll(new RegExp(`["'\`](${ID})["'\`]`, "g"))) found.add(id[1]!);
  }
  return [...found];
}

/** Build one row per ADR rule from the references. */
export function buildRows(rules: { id: string; title: string }[], refs: { rule: string; ref: RuleRef }[]): RuleRow[] {
  return rules.map((rule) => {
    const tests = refs.filter((r) => r.rule === rule.id).map((r) => r.ref);
    const status: Status = tests.some((t) => !t.pending) ? "covered" : tests.length > 0 ? "pending only" : "none";
    return { ...rule, status, tests };
  });
}

/** Rule ids used in references but missing from the ADR. */
export function unknownRules(known: string[], refs: { rule: string }[]): string[] {
  const set = new Set(known);
  return [...new Set(refs.map((r) => r.rule).filter((id) => !set.has(id)))];
}

export function renderTable(rows: RuleRow[], pendingEntries: number): string {
  const count = (status: Status) => rows.filter((row) => row.status === status).length;
  const cell = (row: RuleRow) => {
    if (row.tests.length === 0) return "-";
    const shown = row.tests.slice(0, 6).map((t) => `\`${t.test}\`${t.pending ? " (pending)" : ""}`);
    const more = row.tests.length > 6 ? `, and ${row.tests.length - 6} more` : "";
    return shown.join(", ") + more;
  };
  return [
    "# Multi-player rule coverage",
    "",
    "Generated by `packages/duel-server/scripts/rule-coverage.ts`. Do not edit by hand.",
    "Rules: `docs/adr/0002-multiplayer-duel-rules.md`. A test declares the rules it checks with `rules: [...]`.",
    "",
    `Summary: ${count("covered")} covered, ${count("pending only")} pending only, ${count("none")} none. ${pendingEntries} catalog entries are still pending.`,
    "",
    "| Rule | Text | Status | Tests |",
    "| --- | --- | --- | --- |",
    ...rows.map((row) => `| \`${row.id}\` | ${row.title.replace(/\|/g, "\\|")} | ${row.status} | ${cell(row)} |`),
    "",
  ].join("\n");
}

function walk(directory: string): string[] {
  if (!existsSync(directory)) return [];
  return readdirSync(directory).flatMap((name) => {
    const path = join(directory, name);
    return statSync(path).isDirectory() ? walk(path) : [path];
  });
}

const here = fileURLToPath(new URL(".", import.meta.url));
export const packageRoot = resolve(here, "..");
export const repoRoot = resolve(packageRoot, "../..");

/** Source files that may declare rules (the catalog is read as data, not as text). */
export function declarationFiles(root = packageRoot): string[] {
  const tests = join(root, "tests");
  const nseat = existsSync(tests) ? readdirSync(tests).filter((n) => n.includes("nseat")).map((n) => join(tests, n)) : [];
  return [...walk(join(tests, "scenarios")), ...nseat, ...walk(join(root, "src", "presets"))].filter(
    (file) => /\.(ts|mjs)$/.test(file) && !/scenarios[\\/]multiplayer[\\/]catalog(\.test)?\.ts$/.test(file),
  );
}

export async function collect(root = packageRoot) {
  const refs: { rule: string; ref: RuleRef }[] = [];
  for (const file of declarationFiles(root)) {
    const name = relative(root, file);
    for (const rule of parseRuleDeclarations(readFileSync(file, "utf8"))) refs.push({ rule, ref: { test: name, pending: false } });
  }
  const catalog = (await import(pathToFileURL(join(root, "tests/scenarios/multiplayer/catalog.ts")).href)) as {
    SCENARIOS: { id: string; rules: string[]; pending: boolean }[];
  };
  for (const scenario of catalog.SCENARIOS) {
    for (const rule of scenario.rules) refs.push({ rule, ref: { test: scenario.id, pending: scenario.pending } });
  }
  return { refs, pendingEntries: catalog.SCENARIOS.filter((s) => s.pending).length };
}

async function main() {
  const strict = process.argv.includes("--strict");
  const checkOnly = process.argv.includes("--check");
  const adr = readFileSync(join(repoRoot, "docs/adr/0002-multiplayer-duel-rules.md"), "utf8");
  const rules = parseAdrRules(adr);
  const { refs, pendingEntries } = await collect();
  const unknown = unknownRules(rules.map((r) => r.id), refs);
  const rows = buildRows(rules, refs);
  const table = renderTable(rows, pendingEntries);
  if (!checkOnly) writeFileSync(join(repoRoot, "docs/specs/multiplayer-rule-coverage.md"), table);
  const none = rows.filter((row) => row.status === "none");
  console.log(`${rows.length} rules: ${rows.filter((r) => r.status === "covered").length} covered, ${rows.filter((r) => r.status === "pending only").length} pending only, ${none.length} none.`);
  if (unknown.length > 0) console.error(`Unknown rule ids: ${unknown.join(", ")}`);
  if (none.length > 0) console.log(`No test: ${none.map((row) => row.id).join(", ")}`);
  if (strict && (none.length > 0 || unknown.length > 0)) process.exit(1);
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) await main();
