import { NextRequest } from "next/server";
import { beforeEach, afterEach, expect, it, vi } from "vitest";
const state = vi.hoisted(() => ({ userId: "user_signed_in" as string | null }));
vi.mock("@clerk/nextjs/server", () => ({ clerkMiddleware: (handler: Function) => (req: NextRequest) => handler(async () => ({ userId: state.userId }), req), createRouteMatcher: (patterns: string[]) => (req: NextRequest) => patterns.some(p => new RegExp(`^${p}$`).test(req.nextUrl.pathname)) }));
import proxy from "../proxy";
const request = (path: string, method = "GET") => proxy(new NextRequest(`http://localhost${path}`, { method }), {} as never);
beforeEach(() => { state.userId = "user_signed_in"; vi.stubEnv("E2E_AUTH", "0"); vi.stubEnv("DUEL_FX_LAB", "0"); vi.stubGlobal("fetch", vi.fn(() => { throw new Error("Unexpected I/O"); })); });
afterEach(() => { vi.unstubAllEnvs(); vi.unstubAllGlobals(); });
it.each(["/dashboard", "/api/tournaments"])("allows signed-in access to %s without Discord", async path => { expect((await request(path))?.status).toBe(200); expect(fetch).not.toHaveBeenCalled(); });
it("requires Clerk sessions on both pages and APIs", async () => { state.userId = null; expect((await request("/dashboard"))?.headers.get("location")).toBe("http://localhost/sign-in?redirect_url=%2Fdashboard"); expect((await request("/api/tournaments"))?.status).toBe(401); expect(fetch).not.toHaveBeenCalled(); });
it.each(["/login", "/sign-in", "/sign-up", "/sso-callback", "/access", "/api/auth/session", "/favicon.ico", "/icons/spell.svg"])("opens %s without session lookup", async path => { state.userId = null; expect((await request(path))?.status).toBe(200); expect(fetch).not.toHaveBeenCalled(); });
it("opens only the waitlist POST and protects arbitrary page actions", async () => { state.userId = null; expect((await request("/api/waitlist", "POST"))?.status).toBe(200); expect((await request("/api/waitlist"))?.status).toBe(401); expect((await request("/dashboard", "POST"))?.status).toBe(307); });
it.each(["/dev/fx-lab", "/api/cards/89631139/image"])("opens enabled FX preview %s", async path => { vi.stubEnv("DUEL_FX_LAB", "1"); state.userId = null; expect((await request(path))?.status).toBe(200); });
it("404s the disabled lab", async () => { expect((await request("/dev/fx-lab"))?.status).toBe(404); });
