import { beforeEach, afterEach, expect, it, vi } from "vitest";
const s = vi.hoisted(() => ({ auth: vi.fn(), revoke: vi.fn(), remove: vi.fn(), redirect: vi.fn() }));
vi.mock("@clerk/nextjs/server", () => ({ auth: s.auth, clerkClient: async () => ({ sessions: { revokeSession: s.revoke } }) }));
vi.mock("next/headers", () => ({ cookies: async () => ({ delete: s.remove }) }));
vi.mock("next/navigation", () => ({ redirect: s.redirect }));
import { handleSignOut } from "../src/lib/actions";
beforeEach(() => { vi.clearAllMocks(); vi.stubEnv("E2E_AUTH", "0"); s.auth.mockResolvedValue({ sessionId: "sess_one" }); });
afterEach(() => vi.unstubAllEnvs());
it("revokes the current Clerk session and returns to sign-in", async () => { await handleSignOut(); expect(s.revoke).toHaveBeenCalledWith("sess_one"); expect(s.redirect).toHaveBeenCalledWith("/sign-in"); });
it("clears the offline session without initializing Clerk", async () => { vi.stubEnv("E2E_AUTH", "1"); vi.stubEnv("E2E_AUTH_SECRET", "x".repeat(32)); await handleSignOut(); expect(s.remove).toHaveBeenCalledWith("dd_e2e_session"); expect(s.auth).not.toHaveBeenCalled(); expect(s.revoke).not.toHaveBeenCalled(); });
