import {
  activate, attack, choose, defineScenario, endTurn, expectNotOffered, expectOffered, expectPrompt,
  normalSummon, pickOpponent, select, specialSummon, yes, type DuelistExpect, type Scenario, type Step,
} from "../../support/dsl.js";
import { baseSetup, everySeat, SEATS, type Format, type Seat } from "./seat-kit.js";

const SOURCE = "docs/audits/2026-10-05-hand-card-rules.md";
const ELF = "Mystical Elf";
const AXE = "Axe Raider";
const BLUE = "Blue-Eyes White Dragon";
const KURIBOH = "Kuriboh";
const HONEST = "Honest";
const GORZ = "Gorz the Emissary of Darkness";
const SAGE = "Sage with Eyes of Blue";
const SPIRIT = "Dragon Spirit of White";
const MAX = "Blue-Eyes Chaos MAX Dragon";
const VEILER = "Effect Veiler";

function audit(format: Format, slug: string, code: number, title: string,
  setup: Partial<Record<Seat, object>>, steps: Step[], board: Partial<Record<Seat, DuelistExpect>>,
  rules = ["R-COMMON-SEAT-STATE", "R-FFA-OPP-RESPONSE"],
): Scenario {
  return defineScenario({
    id: `hand-audit-${format}-${slug}`, title: `${format}: ${title}`, source: SOURCE,
    rules, tags: ["multiplayer", "hand-audit", format, `card:${code}`],
    setup: { ...baseSetup(format, setup), skipOpeningDraw: true },
    steps: [...steps, everySeat(format, board)],
  });
}

function cases(format: Format): Scenario[] {
  const holder: Seat = format === "tag" ? "p3" : "p2";
  const victim: Seat = format === "tag" ? "p1" : "p2";
  const other: Seat = "p1";
  const nonBattle: Seat = format === "ffa4" ? "p3" : "p2";
  return [
    audit(format, "kuriboh-damage-calculation", 40640057,
      `${holder} discards Kuriboh at damage calculation and prevents only its team's battle damage`,
      { p0: { monsters: [AXE] }, [holder]: { hand: [KURIBOH] } },
      [attack(AXE, "direct", "p0"), pickOpponent(victim, "p0"),
        expectOffered("activate", { card: KURIBOH, from: "hand" }, holder), activate(KURIBOH, holder)],
      { p0: { monsters: [AXE], hand: [] }, [holder]: { hand: [], grave: [KURIBOH] } }),
    ...(format === "tag" ? [audit(format, "kuriboh-attacked-seat-damage-calculation", 40640057,
      `p1 discards Kuriboh when p0 attacks p1 directly`,
      { p0: { monsters: [AXE] }, p1: { hand: [KURIBOH] } },
      [attack(AXE, "direct", "p0"), pickOpponent("p1", "p0"), expectOffered("activate", KURIBOH, "p1"), activate(KURIBOH, "p1")],
      { p0: { monsters: [AXE], hand: [] }, p1: { hand: [], grave: [KURIBOH] } })] : []),
    ...(format !== "tag" ? [audit(format, "kuriboh-non-battle-seat-is-illegal", 40640057,
      `${nonBattle} keeps Kuriboh when p0 damages p1, because ${nonBattle} takes no battle damage`,
      { p0: { monsters: [AXE] }, [nonBattle]: { hand: [KURIBOH] } },
      [attack(AXE, "direct", "p0"), pickOpponent(other, "p0"), expectPrompt({ by: "p0", context: "action" })],
      { p0: { monsters: [AXE], hand: [] }, p1: { lp: 6300 }, [nonBattle]: { hand: [KURIBOH] } })] : []),
    audit(format, "honest-light-battle-damage-step", 37742478,
      `${holder} sends Honest to the GY during the Damage Step; its LIGHT defender gains the attacker's 1700 ATK`,
      { p0: { monsters: [AXE] }, [victim]: { monsters: [ELF] }, [holder]: { hand: [HONEST], ...(holder === victim ? { monsters: [ELF] } : {}) } },
      [attack(AXE, { card: ELF, owner: victim }, "p0"),
        expectOffered("activate", { card: HONEST, from: "hand" }, holder), activate(HONEST, holder)],
      { p0: { lp: format === "tag" ? 15200 : 7200, grave: [AXE], hand: [] },
        [victim]: { monsters: [ELF], zones: { m0: { card: ELF, attack: 2500 } } },
        [holder]: { hand: [], grave: [HONEST], ...(holder === victim ? { monsters: [ELF], zones: { m0: { card: ELF, attack: 2500 } } } : {}) } }),
    ...(format !== "tag" ? [audit(format, "honest-non-battle-seat-is-illegal", 37742478,
      `${nonBattle} keeps Honest when a different seat's LIGHT monster battles`,
      { p0: { monsters: [AXE] }, p1: { monsters: [ELF] }, [nonBattle]: { hand: [HONEST], monsters: [ELF] } },
      [attack(AXE, { card: ELF, owner: "p1" }, "p0"), expectPrompt({ by: "p0", context: "action" })],
      { p0: { monsters: [AXE], hand: [] }, p1: { lp: 7100, grave: [ELF] }, [nonBattle]: { hand: [HONEST], monsters: [ELF] } })] : []),
    audit(format, "gorz-battle-damage-optional-hand-trigger", 44330098,
      `${holder} summons Gorz after 1700 battle damage and receives a 1700 ATK Token`,
      { p0: { monsters: [AXE] }, [holder]: { hand: [GORZ] } },
      [attack(AXE, "direct", "p0"), pickOpponent(victim, "p0"), expectOffered("activate", GORZ, holder), activate(GORZ, holder)],
      { p0: { monsters: [AXE], hand: [] }, [victim]: { lp: format === "tag" ? 14300 : 6300 },
        [holder]: { lp: format === "tag" ? 14300 : 6300, hand: [], monsters: [GORZ, "Emissary of Darkness Token"],
          zones: { m1: { card: "Emissary of Darkness Token", attack: 1700 } } } }),
    ...(format !== "tag" ? [audit(format, "gorz-other-seat-damage-is-illegal", 44330098,
      `${nonBattle} keeps Gorz when p0 damages p1`,
      { p0: { monsters: [AXE] }, [nonBattle]: { hand: [GORZ] } },
      [attack(AXE, "direct", "p0"), pickOpponent(other, "p0"), expectPrompt({ by: "p0", context: "action" })],
      { p0: { monsters: [AXE], hand: [] }, p1: { lp: 6300 }, [nonBattle]: { hand: [GORZ] } })] : []),
    audit(format, "gorz-controlling-a-card-is-illegal", 44330098,
      `${holder} keeps Gorz after damage because its team controls a Spell`,
      { p0: { monsters: [AXE] }, [holder]: { hand: [GORZ], spells: ["Swords of Concealing Light"] } },
      [attack(AXE, "direct", "p0"), pickOpponent(victim, "p0"), expectPrompt({ by: "p0", context: "action" })],
      { p0: { monsters: [AXE], hand: [] }, [victim]: { lp: format === "tag" ? 14300 : 6300 },
        [holder]: { lp: format === "tag" ? 14300 : 6300, hand: [GORZ], spells: ["Swords of Concealing Light"] } }),
    audit(format, "gorz-effect-damage-bound-to-source", 44330098,
      `${holder} summons Gorz after p0's effect damage and declares p0 for the follow-up 800 damage`,
      { p0: { hand: ["Ookazi"] }, [holder]: { hand: [GORZ] } },
      [activate("Ookazi", "p0"), ...(format === "tag" ? [] : [pickOpponent(holder, "p0")]), expectOffered("activate", GORZ, holder), activate(GORZ, holder),
        ...(format === "tag" ? [] : [pickOpponent("p0", holder)]), expectPrompt({ by: "p0", context: "action" })],
      { p0: { lp: format === "tag" ? 15200 : 7200, hand: [], grave: ["Ookazi"] },
        [holder]: { lp: format === "tag" ? 15200 : 7200, hand: [], monsters: [GORZ] } }),
    audit(format, "sage-own-main-phase-hand-ignition", 8240199,
      `p0 discards Sage, sends its Effect Monster to the GY and summons Blue-Eyes from its own Deck`,
      { p0: { hand: [SAGE], monsters: [VEILER, "The Calculator"], deck: [BLUE, SPIRIT] } },
      [expectOffered("activate", { card: SAGE, from: "hand" }, "p0"), activate({ card: SAGE, from: "hand" }, "p0"),
        select({ card: VEILER, owner: "p0" }), select({ card: BLUE, owner: "p0", from: "deck" })],
      { p0: { hand: [], monsters: [BLUE, "The Calculator"], grave: [SAGE, VEILER] } }),
    audit(format, "sage-no-effect-monster-is-illegal", 8240199,
      `Sage's hand ignition cannot target a Normal Monster`,
      { p0: { hand: [SAGE], monsters: [ELF], deck: [BLUE] } },
      [expectNotOffered("activate", { card: SAGE, from: "hand" }, "p0"), normalSummon(SAGE, "p0")],
      { p0: { hand: [], monsters: [ELF, SAGE] } }),
    audit(format, "sage-non-turn-hand-ignition-is-illegal", 8240199,
      `p2 keeps Sage while p0 resolves a Spell; an ignition effect cannot answer from a non-turn seat`,
      { p0: { hand: ["Pot of Greed"] }, p2: { hand: [SAGE], monsters: ["The Calculator"], deck: [BLUE] } },
      [activate("Pot of Greed", "p0"), expectPrompt({ by: "p0", context: "action" })],
      { p0: { hand: [ELF, ELF], grave: ["Pot of Greed"] }, p2: { hand: [SAGE], monsters: ["The Calculator"] } }),
    audit(format, "dragon-spirit-field-quick-summons-own-hand", 45467446,
      `p2 tributes Dragon Spirit from the field during p0's End Phase and summons Blue-Eyes from its own hand`,
      { p0: { monsters: [AXE] }, p1: { monsters: [AXE] }, p2: { monsters: [SPIRIT], hand: [BLUE] } },
      [endTurn("p0"), expectOffered("activate", { card: SPIRIT, from: "mzone" }, "p2"), activate({ card: SPIRIT, from: "mzone" }, "p2")],
      { p0: { monsters: [AXE], hand: [] }, p1: { monsters: [AXE] }, p2: { hand: [], monsters: [BLUE], grave: [SPIRIT] } }),
    audit(format, "dragon-spirit-hand-has-no-activated-effect", 45467446,
      `Dragon Spirit in the hand is a Normal Monster; its Quick Effect is legal only on the field`,
      { p0: { hand: [SPIRIT, BLUE, "Pot of Greed"] }, p1: { monsters: [AXE] } },
      [expectNotOffered("activate", { card: SPIRIT, from: "hand" }, "p0"), activate("Pot of Greed", "p0")],
      { p0: { hand: [SPIRIT, BLUE, ELF, ELF], grave: ["Pot of Greed"] }, p1: { monsters: [AXE] } }),
    ...(format === "tag" ? [audit(format, "dragon-spirit-cannot-summon-partner-hand", 45467446,
      `p0's Dragon Spirit cannot summon Blue-Eyes from p2's hand`,
      { p0: { monsters: [SPIRIT], hand: ["Pot of Greed"] }, p1: { monsters: [AXE] }, p2: { hand: [BLUE] } },
      [expectNotOffered("activate", SPIRIT, "p0"), activate("Pot of Greed", "p0")],
      { p0: { monsters: [SPIRIT], hand: [ELF, ELF], grave: ["Pot of Greed"] }, p1: { monsters: [AXE] }, p2: { hand: [BLUE] } },
      ["R-TAG-SHARED-CARDS", "R-TAG-PARTNER-COST"])] : []),
    audit(format, "alternative-hand-summon-reveals-own-blue-eyes", 38517737,
      `p0 reveals Blue-Eyes in its hand to summon Alternative; the revealed Blue-Eyes stays in hand`,
      { p0: { hand: ["Blue-Eyes Alternative White Dragon", BLUE] } },
      [expectOffered("specialSummon", "Blue-Eyes Alternative White Dragon", "p0"), specialSummon("Blue-Eyes Alternative White Dragon", "p0"),
        select({ card: BLUE, owner: "p0", from: "hand" })],
      { p0: { monsters: ["Blue-Eyes Alternative White Dragon"], hand: [BLUE] } }),
    audit(format, "alternative-without-blue-eyes-is-illegal", 38517737,
      `Alternative cannot summon itself without a Blue-Eyes to reveal in its own hand`,
      { p0: { hand: ["Blue-Eyes Alternative White Dragon", "Pot of Greed"] } },
      [expectNotOffered("specialSummon", "Blue-Eyes Alternative White Dragon", "p0"), activate("Pot of Greed", "p0")],
      { p0: { hand: ["Blue-Eyes Alternative White Dragon", ELF, ELF], grave: ["Pot of Greed"] } }),
    audit(format, "ancients-hand-has-no-activated-effect", 71039903,
      `The White Stone of Ancients in hand has no activated hand effect`,
      { p0: { hand: ["The White Stone of Ancients", "Pot of Greed"] } },
      [expectNotOffered("activate", { card: "The White Stone of Ancients", from: "hand" }, "p0"), activate("Pot of Greed", "p0")],
      { p0: { hand: ["The White Stone of Ancients", ELF, ELF], grave: ["Pot of Greed"] } }),
    audit(format, "dictator-hand-ignition-sends-own-blue-eyes", 66961194,
      `p0 sends Blue-Eyes from its own Deck to the GY to summon Dictator from hand`,
      { p0: { hand: ["Dictator of D.", BLUE], deck: [BLUE] } },
      [expectOffered("activate", { card: "Dictator of D.", from: "hand" }, "p0"), activate({ card: "Dictator of D.", from: "hand" }, "p0"),
        select({ card: BLUE, owner: "p0", from: "deck" })],
      { p0: { monsters: ["Dictator of D."], hand: [BLUE], grave: [BLUE] } }),
    ...(format !== "tag" ? [audit(format, "gorz-when-misses-timing-after-chain-link-two-damage", 44330098,
      `Gorz stays in p2's hand when Chain Link 2 damages p2 and Chain Link 1 then flips a monster`,
      { p0: { hand: ["Book of Moon"] }, p1: { monsters: [ELF], spells: [{ card: "Chain Strike", pos: "set" }] }, p2: { hand: [GORZ] } },
      [activate("Book of Moon", "p0"), activate("Chain Strike", "p1"), pickOpponent("p2", "p1"),
        expectPrompt({ by: "p0", context: "action" })],
      { p0: { hand: [], grave: ["Book of Moon"] }, p1: { monsters: [ELF], hand: [], grave: ["Chain Strike"], zones: { m0: { card: ELF, pos: "set" } } },
        p2: { hand: [GORZ], lp: 7200 } })] : []),
    audit(format, "chaos-max-hand-has-no-activated-effect", 55410871,
      `Chaos MAX in the hand has no activated hand effect and cannot be Special Summoned without a Ritual effect`,
      { p0: { hand: [MAX, "Pot of Greed"] } },
      [expectNotOffered("activate", { card: MAX, from: "hand" }, "p0"), expectNotOffered("specialSummon", MAX, "p0"), activate("Pot of Greed", "p0")],
      { p0: { hand: [MAX, ELF, ELF], grave: ["Pot of Greed"] } }),
    audit(format, "blue-abyss-hand-ignition", 67886895,
      "p0 discards Deep-Eyes White Dragon, the Blue Abyss and searches a Level 1 LIGHT Tuner",
      { p0: { hand: ["Deep-Eyes White Dragon, the Blue Abyss"], deck: [VEILER] } },
      [activate("Deep-Eyes White Dragon, the Blue Abyss", "p0")],
      { p0: { hand: [VEILER], grave: ["Deep-Eyes White Dragon, the Blue Abyss"] } }),
    audit(format, "blue-abyss-non-turn-hand-trigger", 67886895,
      "p2 summons Blue Abyss from hand when its White Dragon is sent to the GY by p0's Dark Hole",
      { p0: { hand: ["Dark Hole"] }, p2: { hand: ["Deep-Eyes White Dragon, the Blue Abyss"], monsters: [BLUE] } },
      [activate("Dark Hole", "p0"), expectOffered("activate", "Deep-Eyes White Dragon, the Blue Abyss", "p2"),
        activate("Deep-Eyes White Dragon, the Blue Abyss", "p2")],
      { p0: { hand: [], grave: ["Dark Hole"] }, p2: { hand: [], grave: [BLUE], monsters: ["Deep-Eyes White Dragon, the Blue Abyss"],
        zones: { m0: { card: "Deep-Eyes White Dragon, the Blue Abyss", attack: 3000 } } } }),
    audit(format, "phantom-beast-own-battle-destruction", 30397786,
      `${holder} summons White Phantom Beast after its team's monster is destroyed by battle`,
      { p0: { monsters: [AXE] }, [victim]: { monsters: [ELF] }, [holder]: { hand: ["Blue-Eyes White Dragon, the White Phantom Beast"], ...(holder === victim ? { monsters: [ELF] } : {}) } },
      [attack(AXE, { card: ELF, owner: victim }, "p0"), expectOffered("activate", "Blue-Eyes White Dragon, the White Phantom Beast", holder),
        activate("Blue-Eyes White Dragon, the White Phantom Beast", holder), yes(holder)],
      { p0: { hand: [], grave: [AXE] }, [victim]: { lp: format === "tag" ? 15100 : 7100, grave: [ELF] },
        [holder]: { lp: format === "tag" ? 15100 : 7100, hand: [], monsters: ["Blue-Eyes White Dragon, the White Phantom Beast"], ...(holder === victim ? { grave: [ELF] } : {}) } }),
    audit(format, "maiden-white-hand-ignition", 17947697,
      "p0 sends Maiden of White from hand to the GY and places True Light face up",
      { p0: { hand: ["Maiden of White"], deck: ["True Light"] } },
      [activate("Maiden of White", "p0")],
      { p0: { hand: [], grave: ["Maiden of White"], spells: ["True Light"] } }),
    audit(format, "chronicle-magician-hand-summon-trigger", 60948488,
      "p0 summons Chronicle Magician from hand after White Dragon is summoned, then increases its ATK/DEF",
      { p0: { hand: ["Monster Reborn", "Chronicle Magician"], grave: [BLUE] } },
      [activate("Monster Reborn", "p0"), expectOffered("activate", "Chronicle Magician", "p0"), activate("Chronicle Magician", "p0"), yes("p0")],
      { p0: { hand: [], grave: ["Monster Reborn"], monsters: [BLUE, "Chronicle Magician"], zones: { m0: { card: BLUE, attack: 5500, defense: 5000 } } } }),
    audit(format, "white-lightning-non-turn-hand-chain", 15613529,
      `${holder} summons Mystical Elf - White Lightning and negates p0's field monster effect`,
      { p0: { monsters: ["Card Trooper"] }, [holder]: { hand: ["Mystical Elf - White Lightning"], monsters: [BLUE] } },
      [activate("Card Trooper", "p0"), choose("3", "p0"), expectOffered("activate", "Mystical Elf - White Lightning", holder), activate("Mystical Elf - White Lightning", holder)],
      { p0: { monsters: ["Card Trooper"], grave: [ELF, ELF, ELF], zones: { m0: { card: "Card Trooper", attack: 400 } } },
        [holder]: { hand: [], monsters: [BLUE, "Mystical Elf - White Lightning"] } }),
    audit(format, "rosepamela-non-turn-hand-quick", 65302903,
      `${holder} reveals Rosepamela during p0's turn, adds Dominus Purge, then discards a card from its own hand`,
      { p0: { hand: ["Pot of Greed"] }, [holder]: { hand: ["Dominusteer Rosepamela", ELF], deck: ["Dominus Purge"] } },
      [activate("Pot of Greed", "p0"), expectOffered("activate", "Dominusteer Rosepamela", holder), activate("Dominusteer Rosepamela", holder),
        select({ card: ELF, owner: holder, from: "hand" })],
      { p0: { hand: [ELF, ELF], grave: ["Pot of Greed"] }, [holder]: { hand: ["Dominusteer Rosepamela", "Dominus Purge"], grave: [ELF] } }),
    audit(format, "neo-kaiser-hand-ignition", 54332792,
      "p0 summons Neo Kaiser Sea Horse from hand while it controls White Dragon",
      { p0: { hand: ["Neo Kaiser Sea Horse"], monsters: [BLUE] } },
      [activate("Neo Kaiser Sea Horse", "p0")],
      { p0: { hand: [], monsters: [BLUE, "Neo Kaiser Sea Horse"] } }),
  ];
}

/** Every case runs against both prepared multi cores, with a real outcome for every seat. */
export const HAND_EFFECTS_AUDIT_SCENARIOS: Scenario[] = (["ffa3", "ffa4", "tag"] as const).flatMap(format =>
  cases(format).flatMap(scenario => [scenario, defineScenario({
    ...scenario, id: `${scenario.id}-domain`, title: `Domain ${scenario.title}`, tags: [...scenario.tags, "domain"],
    setup: { ...scenario.setup, mode: "domain", ...Object.fromEntries(SEATS[format].map(seat =>
      [seat, { ...scenario.setup[seat], deckMaster: BLUE }])) },
  })]),
);
