// Monster cards whose effect Special Summons the card itself or tokens to the field of an opponent (the table and the rule are in
// opponent-field-effects.ts). Each card needs its own trigger (a flip, a destruction, a battle, a discard), so each row has its own steps.

import { activate, attack, changePosition, choose, endTurn, expectPickSeats, expectPrompt, no, normalSummon, pickOpponent, select, yes } from "../../support/dsl.js";
import { ELF } from "./nseat-scenarios.js";
import { effectScenarios, type EffectSpec } from "./opponent-field-effects.js";

const set = (card: string) => ({ card, pos: "set" as const });
const MAGICIAN = "Dark Magician";

const SPECS: EffectSpec[] = [
  {
    code: 561300, name: "Poisonous Viper", slug: "poisonous-viper", does: "Special Summons itself from the hand in Defense Position (no opponent has a monster)",
    p0: { hand: ["Poisonous Viper"] },
    opp: {},
    partner: {},
    steps: [activate("Poisonous Viper", "p0")],
    p0End: { hand: [] },
    gain: { monsters: ["Poisonous Viper"] },
  },
  {
    code: 7392745, name: "Chewbone", slug: "chewbone", does: "Special Summons 3 Chewbone Tokens when it is flipped",
    p0: { monsters: [set("Chewbone")] },
    steps: [changePosition("Chewbone", "p0")],
    p0End: { monsters: ["Chewbone"] },
    gain: { tokens: { count: 3 } },
  },
  {
    code: 30069398, name: "Wall of Ivy", slug: "wall-of-ivy", does: "Special Summons 1 Ivy Token when it is flipped",
    p0: { monsters: [set("Wall of Ivy")] },
    steps: [changePosition("Wall of Ivy", "p0")],
    p0End: { monsters: ["Wall of Ivy"] },
    gain: { tokens: { count: 1 } },
  },
  {
    code: 7623640, name: "Ceruli, Guru of Dark World", slug: "ceruli", does: "Special Summons itself in Defense Position when it is discarded by an effect",
    p0: { hand: ["Graceful Charity", "Ceruli, Guru of Dark World"], deck: ["Giant Rat", "Giant Rat", "Giant Rat"] },
    steps: [activate("Graceful Charity", "p0"), select("Ceruli, Guru of Dark World", "Giant Rat")],
    p0End: { hand: ["Giant Rat", "Giant Rat"], grave: ["Graceful Charity", "Giant Rat"] },
    gain: { monsters: ["Ceruli, Guru of Dark World"] },
  },
  {
    code: 74440055, name: "Cactus Fighter", slug: "cactus-fighter", does: "Special Summons a Cactus Token when it destroys a monster by battle",
    attackFirstTurn: true,
    noPick: true,
    p0: { monsters: ["Cactus Fighter"] },
    tgt: { monsters: [{ card: "Kuriboh", pos: "def" }] },
    steps: (roles) => [attack("Cactus Fighter", { card: "Kuriboh", owner: roles.tgt }, "p0")],
    p0End: { monsters: ["Cactus Fighter"] },
    tgtEnd: { grave: ["Kuriboh"], tokens: { count: 1 } },
  },
  {
    code: 37129797, name: "Vampire Sucker", slug: "vampire-sucker", does: "Special Summons a monster of an opponent Graveyard in Defense Position",
    p0: { monsters: ["Vampire Sucker"] },
    tgt: { monsters: [ELF], grave: [MAGICIAN] },
    // Only the target opponent has a legal GY monster in FFA.
    noPick: (roles) => roles.format !== "tag",
    // An opponent prompt must fail the action-context check.
    steps: (roles) => [activate("Vampire Sucker", "p0"), ...(roles.format !== "tag" ? [expectPrompt({ by: "p0", context: "action" })] : [])],
    p0End: { monsters: ["Vampire Sucker"] },
    tgtEnd: { monsters: [ELF, MAGICIAN] },
  },
  {
    code: 38041940, name: "Seed of Flame", slug: "seed-of-flame", does: "Special Summons a Plant from the own Graveyard and a Plant Token when it is destroyed by an effect",
    p0: { hand: ["Dark Hole"], monsters: ["Seed of Flame"], grave: ["Dark Plant"] },
    opp: {},
    partner: {},
    steps: [activate("Dark Hole", "p0"), yes("p0")],
    p0End: { monsters: ["Dark Plant"], grave: ["Dark Hole", "Seed of Flame"] },
    gain: { tokens: { count: 1 } },
  },  {
    code: 11677278, name: "Mimighoul Armor", slug: "mimighoul-armor", does: "Special Summons itself from the hand face-down in Defense Position",
    p0: { hand: ["Mimighoul Armor"] },
    opp: {},
    partner: {},
    steps: [activate("Mimighoul Armor", "p0")],
    p0End: { hand: [] },
    gain: { monsters: ["Mimighoul Armor"] },
  },
  {
    code: 43066927, name: "Mimighoul Fairy", slug: "mimighoul-fairy", does: "Special Summons itself from the hand face-down in Defense Position",
    p0: { hand: ["Mimighoul Fairy"] },
    opp: {},
    partner: {},
    steps: [activate("Mimighoul Fairy", "p0")],
    p0End: { hand: [] },
    gain: { monsters: ["Mimighoul Fairy"] },
  },
  {
    code: 82933935, name: "Mimighoul Flower", slug: "mimighoul-flower", does: "Special Summons itself from the hand face-down in Defense Position",
    p0: { hand: ["Mimighoul Flower"] },
    opp: {},
    partner: {},
    steps: [activate("Mimighoul Flower", "p0")],
    p0End: { hand: [] },
    gain: { monsters: ["Mimighoul Flower"] },
  },
  {
    code: 81522098, name: "Mimighoul Dragon", slug: "mimighoul-dragon", does: "Special Summons itself from the hand face-down in Defense Position",
    p0: { hand: ["Mimighoul Dragon"] },
    opp: {},
    partner: {},
    steps: [activate("Mimighoul Dragon", "p0")],
    p0End: { hand: [] },
    gain: { monsters: ["Mimighoul Dragon"] },
  },
  {
    code: 23920796, name: "Mimighoul Cerberus", slug: "mimighoul-cerberus", does: "Special Summons itself from the hand face-down in Defense Position",
    p0: { hand: ["Mimighoul Cerberus"] },
    opp: {},
    partner: {},
    steps: [activate("Mimighoul Cerberus", "p0")],
    p0End: { hand: [] },
    gain: { monsters: ["Mimighoul Cerberus"] },
  },
  {
    code: 50415441, name: "Mimighoul Archfiend", slug: "mimighoul-archfiend", does: "Special Summons itself from the hand face-down in Defense Position",
    p0: { hand: ["Mimighoul Archfiend"] },
    opp: {},
    partner: {},
    steps: [activate("Mimighoul Archfiend", "p0")],
    p0End: { hand: [] },
    gain: { monsters: ["Mimighoul Archfiend"] },
  },  {
    code: 22404675, name: "Mithra the Thunder Vassal", slug: "mithra-the-thunder-vassal", does: "Special Summons a Vassal Token in Defense Position",
    p0: { hand: ["Mithra the Thunder Vassal"] },
    steps: [activate("Mithra the Thunder Vassal", "p0")],
    p0End: { monsters: ["Mithra the Thunder Vassal"], hand: [] },
    gain: { tokens: { count: 1 } },
  },
  {
    code: 22411609, name: "Volcanic Trooper", slug: "volcanic-trooper", does: "Special Summons a Bomb Token",
    p0: { hand: ["Giant Rat"], monsters: ["Volcanic Trooper"] },
    steps: [activate("Volcanic Trooper", "p0")],
    p0End: { monsters: ["Volcanic Trooper"], hand: [], grave: ["Giant Rat"] },
    gain: { tokens: { count: 1 } },
  },
  {
    code: 25131968, name: "Ken the Warrior Dragon", slug: "ken-the-warrior-dragon", does: "Special Summons Gen the Diamond Tiger from the deck in Defense Position",
    p0: { monsters: ["Ken the Warrior Dragon"], deck: ["Gen the Diamond Tiger"] },
    steps: [activate("Ken the Warrior Dragon", "p0")],
    p0End: { monsters: ["Ken the Warrior Dragon"] },
    gain: { monsters: ["Gen the Diamond Tiger"] },
  },
  {
    code: 52126602, name: "Gen the Diamond Tiger", slug: "gen-the-diamond-tiger", does: "Special Summons Ken the Warrior Dragon from the deck in Defense Position",
    p0: { monsters: ["Gen the Diamond Tiger"], deck: ["Ken the Warrior Dragon"] },
    steps: [activate("Gen the Diamond Tiger", "p0")],
    then: [select("Mystical Elf")],
    p0End: { monsters: ["Gen the Diamond Tiger"], hand: ["Mystical Elf"], grave: ["Mystical Elf"] },
    gain: { monsters: ["Ken the Warrior Dragon"] },
  },  {
    code: 54191698, name: "Number 29: Mannequin Cat", slug: "number-29-mannequin-cat", does: "Special Summons a monster of an opponent Graveyard",
    p0: { monsters: [{ card: "Number 29: Mannequin Cat", materials: [ELF, ELF] }] },
    tgt: { monsters: [ELF], grave: [MAGICIAN] },
    // Only the target opponent has a legal GY monster in FFA. The detach choice still opens.
    noPick: (roles) => roles.format !== "tag",
    // The cost is a card choice; after it, only the optional trigger prompt opens.
    // An opponent prompt must fail the card-kind or yes/no-option check.
    steps: (roles) => [activate("Number 29: Mannequin Cat", "p0"), ...(roles.format !== "tag" ? [expectPrompt({ by: "p0", kind: "cards" })] : [])],
    then: (roles) => [select(ELF), ...(roles.format !== "tag" ? [expectPrompt({ by: "p0", offers: ["yes", "no"] })] : []), no("p0")],
    p0End: { monsters: ["Number 29: Mannequin Cat"], grave: ["Mystical Elf"] },
    tgtEnd: { monsters: [ELF, MAGICIAN] },
  },
  {
    code: 44689688, name: "Jurrac Spinos", slug: "jurrac-spinos", does: "Special Summons a Jurrac Token when it destroys a monster by battle",
    attackFirstTurn: true,
    noPick: true,
    p0: { monsters: ["Jurrac Spinos"] },
    tgt: { monsters: [{ card: "Kuriboh", pos: "def" }] },
    steps: (roles) => [attack("Jurrac Spinos", { card: "Kuriboh", owner: roles.tgt }, "p0")],
    p0End: { monsters: ["Jurrac Spinos"] },
    tgtEnd: { grave: ["Kuriboh"], tokens: { count: 1 } },
  },
  {
    code: 48228390, name: "Pyrite Knight", slug: "pyrite-knight", does: "Special Summons a Pyrite Token",
    p0: { hand: ["Pyrite Knight"], monsters: ["Gaia The Fierce Knight"] },
    steps: [activate("Pyrite Knight", "p0")],
    p0End: { hand: ["Gaia The Fierce Knight"], monsters: ["Pyrite Knight"] },
    gain: { tokens: { count: 1 } },
  },
  {
    code: 41141943, name: "Superheavy Samurai Transporter", slug: "superheavy-samurai-transporter", does: "Special Summons a monster from the hand of its controller in Defense Position",
    p0: { monsters: ["Superheavy Samurai Transporter"], hand: ["Giant Rat"] },
    steps: [activate("Superheavy Samurai Transporter", "p0")],
    p0End: { hand: ["Mystical Elf"], grave: ["Superheavy Samurai Transporter"] },
    gain: { monsters: ["Giant Rat"] },
  },
  {
    code: 26964762, name: "Destiny HERO - Dark Angel", slug: "destiny-hero-dark-angel", does: "Special Summons a Destiny HERO from the own Graveyard in Defense Position",
    p0: { hand: ["Destiny HERO - Dark Angel"], grave: ["Destiny HERO - Malicious", "Destiny HERO - Diamond Dude", "Destiny HERO - Denier"] },
    steps: [activate("Destiny HERO - Dark Angel", "p0")],
    then: [select("Destiny HERO - Malicious")],
    p0End: { hand: [], grave: ["Destiny HERO - Diamond Dude", "Destiny HERO - Denier", "Destiny HERO - Dark Angel"] },
    gain: { monsters: ["Destiny HERO - Malicious"] },
  },
  {
    code: 39829561, name: "Destiny HERO - Departed", slug: "destiny-hero-departed", does: "Special Summons itself from the Graveyard in the Standby Phase of its owner",
    p0: { grave: ["Destiny HERO - Departed"] },
    steps: [],
    p0End: { grave: [] },
    gain: { monsters: ["Destiny HERO - Departed"] },
  },
  {
    code: 69811710, name: "Girsu, the Orcust Mekk-Knight", slug: "girsu", does: "Special Summons a World Legacy Token",
    p0: { monsters: ["Girsu, the Orcust Mekk-Knight"] },
    partner: {},
    steps: [activate("Girsu, the Orcust Mekk-Knight", "p0")],
    p0End: { monsters: ["Girsu, the Orcust Mekk-Knight"], tokens: { count: 1 } },
    gain: { tokens: { count: 1 } },
  },
  {
    code: 82012319, name: "Scrap Golem", slug: "scrap-golem", does: "Special Summons a Scrap monster from the Graveyard of its controller",
    p0: { monsters: ["Scrap Golem"], grave: ["Scrap Chimera"] },
    steps: [activate("Scrap Golem", "p0")],
    then: [choose("opponent's field", "p0")],
    p0End: { monsters: ["Scrap Golem"], grave: [] },
    gain: { monsters: ["Scrap Chimera"] },
  },
  {
    code: 9400127, name: "Flogos, the Ogdoadic Boundless", slug: "flogos", does: "Special Summons a monster from the Graveyard of an opponent",
    p0: { hand: ["Monster Reborn"], grave: ["Flogos, the Ogdoadic Boundless"] },
    tgt: { monsters: [ELF], grave: [MAGICIAN] },
    // Monster Reborn reads either GY. Only the target opponent has a legal GY monster for Flogos in FFA.
    noPick: (roles) => roles.format !== "tag",
    // An opponent prompt must fail the card-kind or action-context check.
    steps: (roles) => [activate("Monster Reborn", "p0"), ...(roles.format !== "tag" ? [expectPrompt({ by: "p0", kind: "cards" })] : []), select("Flogos, the Ogdoadic Boundless"), yes("p0"), ...(roles.format !== "tag" ? [expectPrompt({ by: "p0", context: "action" })] : [])],
    then: (roles) => roles.format === "tag" ? [select({ card: ELF, owner: roles.tgt })] : [],
    p0End: { hand: [], grave: ["Monster Reborn"], monsters: ["Flogos, the Ogdoadic Boundless"] },
    tgtEnd: { monsters: [MAGICIAN], grave: [ELF] },
  },
  {
    code: 78783557, name: "Veidos the Eruption Dragon of Extinction", slug: "veidos", does: "Special Summons itself from the hand",
    p0: { hand: ["Veidos the Eruption Dragon of Extinction"], field: "Sogen" },
    steps: [activate("Veidos the Eruption Dragon of Extinction", "p0")],
    p0End: { hand: [], spells: [], grave: ["Sogen"] },
    gain: { monsters: ["Veidos the Eruption Dragon of Extinction"] },
  },
  {
    code: 82773292, name: "Indulged Darklord", slug: "indulged-darklord", does: "Special Summons a Darklord from the hand or the Deck",
    p0: { hand: ["Indulged Darklord"], deck: ["Darklord Zerato", "Darklord Marie"] },
    steps: [normalSummon("Indulged Darklord", "p0"), yes("p0")],
    then: [select("Darklord Zerato")],
    p0End: { monsters: ["Indulged Darklord"], hand: ["Darklord Marie"] },
    gain: { monsters: ["Darklord Zerato"] },
  },
  {
    code: 88124568, name: "SPYRAL Double Agent", slug: "spyral-double-agent", does: "Special Summons itself from the hand in Defense Position",
    p0: { hand: ["SPYRAL Double Agent"], grave: ["SPYRAL Super Agent"] },
    steps: [activate("SPYRAL Double Agent", "p0")],
    p0End: { hand: [], grave: ["SPYRAL Super Agent"] },
    gain: { monsters: ["SPYRAL Double Agent"] },
  },
  {
    code: 71015787, name: "Silent Wobby", slug: "silent-wobby", does: "Special Summons itself from the hand (its new controller draws 1 card and p0, the opponent of that seat, gains 2000 LP)",
    p0: { hand: ["Silent Wobby"] },
    steps: [activate("Silent Wobby", "p0")],
    p0End: (roles) => ({ hand: [], lp: roles.format === "tag" ? 18000 : 10000 }),
    partnerEnd: { monsters: ["Battle Ox"], lp: 18000 },
    gain: { monsters: ["Silent Wobby"] },
  },
  {
    code: 68378605, name: "Vodnika the Fountain Spirit", slug: "vodnika", does: "Special Summons a Level 10 monster from the Graveyard of its controller",
    p0: { monsters: ["Vodnika the Fountain Spirit"], grave: ["Behemoth the King of a Hundred Battles"] },
    steps: [activate("Vodnika the Fountain Spirit", "p0")],
    p0End: { monsters: ["Vodnika the Fountain Spirit"], grave: [] },
    gain: { monsters: ["Behemoth the King of a Hundred Battles"] },
  },
  {
    code: 26913989, name: "Geistgrinder Golem", slug: "geistgrinder-golem", does: "Special Summons itself from the hand",
    p0: { hand: ["Geistgrinder Golem", "Yubel"] },
    steps: [activate("Geistgrinder Golem", "p0")],
    p0End: { hand: ["Yubel"] },
    gain: { monsters: ["Geistgrinder Golem"] },
  },
  {
    code: 82994509, name: "Horseytail", slug: "horseytail", does: "Special Summons a Horseytail Token to the opponent that destroyed it by battle",
    attackFirstTurn: true,
    noPick: true,
    tgt: { monsters: ["Battle Ox"] },
    p0: { monsters: [{ card: "Horseytail", pos: "def" }] },
    steps: (roles) => [
      ...(["p0", "p1", "p2", "p3"] as const).slice(0, (["p0", "p1", "p2", "p3"] as const).indexOf(roles.tgt)).map((seat) => endTurn(seat)),
      attack("Battle Ox", { card: "Horseytail", owner: "p0" }, roles.tgt),
    ],
    p0End: { grave: ["Horseytail"] },
    tgtEnd: { monsters: ["Battle Ox"], tokens: { count: 1 } },
  },
  {
    code: 81003500, name: "Elemental HERO Necroid Shaman", slug: "elemental-hero-necroid-shaman", does: "Special Summons a monster from the Graveyard of an opponent",
    p0: { hand: ["Polymerization"], monsters: ["Elemental HERO Wildheart", "Elemental HERO Necroshade"], extra: ["Elemental HERO Necroid Shaman"] },
    tgt: { monsters: [ELF], grave: [MAGICIAN] },
    // R-FFA-OPP-ONE: the field target is automatic in FFA. Its destruction adds a second GY choice.
    noPick: (roles) => roles.format !== "tag",
    steps: (roles) => [activate("Polymerization", "p0"), select("Elemental HERO Wildheart", "Elemental HERO Necroshade"), ...(roles.format !== "tag" ? [expectPickSeats(roles.opponents, "p0"), pickOpponent(roles.tgt, "p0")] : [select({ card: ELF, owner: roles.tgt })])],
    then: [select(MAGICIAN)],
    p0End: { monsters: ["Elemental HERO Necroid Shaman"], grave: ["Polymerization", "Elemental HERO Wildheart", "Elemental HERO Necroshade"] },
    tgtEnd: { grave: [ELF], monsters: [MAGICIAN] },
  },
  {
    code: 66661678, name: "Royal Knight of the Ice Barrier", slug: "royal-knight-of-the-ice-barrier", does: "Special Summons an Ice Barrier Token when it is Tribute Summoned",
    p0: { hand: ["Royal Knight of the Ice Barrier"], monsters: ["Giant Rat"] },
    steps: [normalSummon("Royal Knight of the Ice Barrier", "p0"), select("Giant Rat")],
    p0End: { monsters: ["Royal Knight of the Ice Barrier"], grave: ["Giant Rat"] },
    gain: { tokens: { count: 1 } },
  },
  {
    code: 57844634, name: "Nimble Musasabi", slug: "nimble-musasabi", does: "Special Summons another Nimble Musasabi from the Deck to the opponent that destroyed it by battle",
    attackFirstTurn: true,
    noPick: true,
    tgt: { monsters: ["Battle Ox"] },
    p0: { monsters: [{ card: "Nimble Musasabi", pos: "def" }], deck: ["Nimble Musasabi"] },
    steps: (roles) => [
      ...(["p0", "p1", "p2", "p3"] as const).slice(0, (["p0", "p1", "p2", "p3"] as const).indexOf(roles.tgt)).map((seat) => endTurn(seat)),
      attack("Battle Ox", { card: "Nimble Musasabi", owner: "p0" }, roles.tgt),
      yes("p0"),
    ],
    p0End: { grave: ["Nimble Musasabi"] },
    tgtEnd: (roles) => ({ monsters: ["Battle Ox", "Nimble Musasabi"], lp: roles.format === "tag" ? 15500 : 7500 }),
    othersEnd: (roles) => ({ monsters: [ELF], lp: roles.format === "tag" ? 15500 : 8000 }),
  },
  {
    code: 65676461, name: "Number 32: Shark Drake", slug: "number-32-shark-drake", does: "Special Summons the monster it destroyed by battle",
    attackFirstTurn: true,
    noPick: true,
    p0: { monsters: [{ card: "Number 32: Shark Drake", materials: [ELF, ELF] }] },
    tgt: { monsters: [{ card: "Kuriboh", pos: "def" }] },
    steps: (roles) => [attack("Number 32: Shark Drake", { card: "Kuriboh", owner: roles.tgt }, "p0"), yes("p0"), select(ELF)],
    p0End: { monsters: ["Number 32: Shark Drake"], grave: [ELF] },
    tgtEnd: { monsters: ["Kuriboh"] },
  },
  {
    code: 59900655, name: "Gold Pride - Nytro Head", slug: "gold-pride-nytro-head", does: "Special Summons a Nytro Token in the Standby Phase of an opponent",
    p0: { monsters: ["Gold Pride - Nytro Head"] },
    steps: [endTurn("p0"), yes("p0")],
    p0End: { monsters: ["Gold Pride - Nytro Head"] },
    gain: { tokens: { count: 1 } },
  },
  {
    code: 63013339, name: "Sky Striker Ace - Camellia", slug: "sky-striker-ace-camellia", does: "Special Summons itself when it is sent to the Graveyard",
    p0: { hand: ["Tribute to The Doomed", "Giant Rat"], monsters: ["Sky Striker Ace - Camellia"] },
    steps: [activate("Tribute to The Doomed", "p0"), select("Sky Striker Ace - Camellia"), yes("p0")],
    then: (roles) => roles.format === "tag" ? [select({ card: ELF, owner: roles.tgt })] : [],
    p0End: { grave: ["Giant Rat", "Tribute to The Doomed"] },
    tgtEnd: { monsters: ["Sky Striker Ace - Camellia"], grave: [ELF] },
  },
  {
    code: 65477143, name: "Abyss Actor - Liberty Dramatist", slug: "abyss-actor-liberty-dramatist", does: "Special Summons itself from the Pendulum Zone when a monster attacks",
    attackFirstTurn: true,
    noPick: true,
    p0: { pendulum: ["Abyss Actor - Liberty Dramatist", null], monsters: ["Battle Ox"], hand: ["Giant Rat"] },
    tgt: { monsters: [{ card: "Kuriboh", pos: "def" }] },
    steps: (roles) => [attack("Battle Ox", { card: "Kuriboh", owner: roles.tgt }, "p0"), yes("p0"), yes("p0"), select("Kuriboh")],
    p0End: { monsters: ["Battle Ox"], spells: [], hand: [], grave: ["Giant Rat"] },
    tgtEnd: { monsters: ["Abyss Actor - Liberty Dramatist"], grave: ["Kuriboh"] },
  },
  {
    code: 40343749, name: "House Duston", slug: "house-duston", does: "Special Summons a Duston to its controller and a Duston to the opponent that destroyed it by battle",
    attackFirstTurn: true,
    noPick: true,
    tgt: { monsters: ["Battle Ox"] },
    p0: { monsters: [{ card: "House Duston", pos: "def" }], deck: ["Blue Duston", "Red Duston"] },
    steps: (roles) => [
      ...(["p0", "p1", "p2", "p3"] as const).slice(0, (["p0", "p1", "p2", "p3"] as const).indexOf(roles.tgt)).map((seat) => endTurn(seat)),
      attack("Battle Ox", { card: "House Duston", owner: "p0" }, roles.tgt),
      yes("p0"),
      select("Blue Duston"),
    ],
    p0End: { monsters: ["Blue Duston"], grave: ["House Duston"] },
    tgtEnd: { monsters: ["Battle Ox", "Red Duston"] },
  },
  {
    code: 3685372, name: "Gimmick Puppet Fanatix Machinix", slug: "gimmick-puppet-fanatix-machinix", does: "Special Summons a monster from a Graveyard in Defense Position",
    p0: { monsters: [{ card: "CXyz Gimmick Puppet Fanatix Machinix", materials: [ELF, ELF, ELF] }], grave: ["Kuriboh"] },
    steps: [activate("CXyz Gimmick Puppet Fanatix Machinix", "p0")],
    then: [select(ELF), select("Kuriboh")],
    p0End: { monsters: ["CXyz Gimmick Puppet Fanatix Machinix"], grave: [ELF] },
    gain: { monsters: ["Kuriboh"] },
  },
  {
    code: 47126872, name: "Space-Time Police", slug: "space-time-police", does: "Sets the monster it banished (of p1) on the field of the opponent that destroyed it, when it leaves the field",
    attackFirstTurn: true,
    noPick: true,
    p0: { hand: ["Monster Reborn"], grave: ["Space-Time Police"] },
    tgt: { monsters: [MAGICIAN, ELF] },
    steps: (roles) => [
      activate("Monster Reborn", "p0"),
      // Monster Reborn reads either GY. The declaration is for Space-Time Police's banish trigger.
      ...(roles.format !== "tag" ? [expectPickSeats(roles.opponents, "p0"), pickOpponent(roles.others[0], "p0")] : [select({ card: ELF, owner: roles.others[0] })]),
      ...(["p0", "p1", "p2", "p3"] as const).slice(0, (["p0", "p1", "p2", "p3"] as const).indexOf(roles.tgt)).map((seat) => endTurn(seat)),
      attack(MAGICIAN, { card: "Space-Time Police", owner: "p0" }, roles.tgt),
    ],
    p0End: (roles) => ({ hand: [], grave: ["Monster Reborn", "Space-Time Police"], lp: roles.format === "tag" ? 15800 : 7800 }),
    tgtEnd: { monsters: [MAGICIAN, ELF, ELF] },
    seatEnd: { p1: { monsters: [] } },
    partnerEnd: { monsters: ["Battle Ox"], lp: 15800 },
  },
];

export const MONSTER_EFFECT_SCENARIOS = SPECS.flatMap(effectScenarios);
