// Monster cards whose effect Special Summons the card itself or tokens to the field of an opponent (the table and the rule are in
// opponent-field-effects.ts). Each card needs its own trigger (a flip, a destruction, a battle, a discard), so each row has its own steps.

import { activate, attack, changePosition, no, select, yes } from "../../support/dsl.js";
import { ELF } from "./nseat-scenarios.js";
import { effectScenarios, type EffectSpec } from "./opponent-field-effects.js";

const set = (card: string) => ({ card, pos: "set" as const });
const MAGICIAN = "Dark Magician";

const SPECS: EffectSpec[] = [
  {
    code: 561300, name: "Poisonous Viper", slug: "poisonous-viper", does: "Special Summons itself from the hand in Defense Position (no opponent has a monster)",
    p0: { hand: ["Poisonous Viper"] },
    opp: {},
    partner: {},
    steps: [activate("Poisonous Viper", "p0")],
    p0End: { hand: [] },
    gain: { monsters: ["Poisonous Viper"] },
  },
  {
    code: 7392745, name: "Chewbone", slug: "chewbone", does: "Special Summons 3 Chewbone Tokens when it is flipped",
    p0: { monsters: [set("Chewbone")] },
    steps: [changePosition("Chewbone", "p0")],
    p0End: { monsters: ["Chewbone"] },
    gain: { tokens: { count: 3 } },
  },
  {
    code: 30069398, name: "Wall of Ivy", slug: "wall-of-ivy", does: "Special Summons 1 Ivy Token when it is flipped",
    p0: { monsters: [set("Wall of Ivy")] },
    steps: [changePosition("Wall of Ivy", "p0")],
    p0End: { monsters: ["Wall of Ivy"] },
    gain: { tokens: { count: 1 } },
  },
  {
    code: 7623640, name: "Ceruli, Guru of Dark World", slug: "ceruli", does: "Special Summons itself in Defense Position when it is discarded by an effect",
    p0: { hand: ["Graceful Charity", "Ceruli, Guru of Dark World"], deck: ["Giant Rat", "Giant Rat", "Giant Rat"] },
    steps: [activate("Graceful Charity", "p0"), select("Ceruli, Guru of Dark World", "Giant Rat")],
    p0End: { hand: ["Giant Rat", "Giant Rat"], grave: ["Graceful Charity", "Giant Rat"] },
    gain: { monsters: ["Ceruli, Guru of Dark World"] },
  },
  {
    code: 74440055, name: "Cactus Fighter", slug: "cactus-fighter", does: "Special Summons a Cactus Token when it destroys a monster by battle",
    attackFirstTurn: true,
    noPick: true,
    p0: { monsters: ["Cactus Fighter"] },
    tgt: { monsters: [{ card: "Kuriboh", pos: "def" }] },
    steps: (roles) => [attack("Cactus Fighter", { card: "Kuriboh", owner: roles.tgt }, "p0")],
    p0End: { monsters: ["Cactus Fighter"] },
    tgtEnd: { grave: ["Kuriboh"], tokens: { count: 1 } },
  },
  {
    code: 37129797, name: "Vampire Sucker", slug: "vampire-sucker", does: "Special Summons a monster of an opponent Graveyard in Defense Position",
    p0: { monsters: ["Vampire Sucker"] },
    tgt: { monsters: [ELF], grave: [MAGICIAN] },
    steps: [activate("Vampire Sucker", "p0")],
    p0End: { monsters: ["Vampire Sucker"] },
    tgtEnd: { monsters: [ELF, MAGICIAN] },
  },
  {
    code: 38041940, name: "Seed of Flame", slug: "seed-of-flame", does: "Special Summons a Plant from the own Graveyard and a Plant Token when it is destroyed by an effect",
    p0: { hand: ["Dark Hole"], monsters: ["Seed of Flame"], grave: ["Dark Plant"] },
    opp: {},
    partner: {},
    steps: [activate("Dark Hole", "p0"), yes("p0")],
    p0End: { monsters: ["Dark Plant"], grave: ["Dark Hole", "Seed of Flame"] },
    gain: { tokens: { count: 1 } },
  },  {
    code: 11677278, name: "Mimighoul Armor", slug: "mimighoul-armor", does: "Special Summons itself from the hand face-down in Defense Position",
    p0: { hand: ["Mimighoul Armor"] },
    opp: {},
    partner: {},
    steps: [activate("Mimighoul Armor", "p0")],
    p0End: { hand: [] },
    gain: { monsters: ["Mimighoul Armor"] },
  },
  {
    code: 43066927, name: "Mimighoul Fairy", slug: "mimighoul-fairy", does: "Special Summons itself from the hand face-down in Defense Position",
    p0: { hand: ["Mimighoul Fairy"] },
    opp: {},
    partner: {},
    steps: [activate("Mimighoul Fairy", "p0")],
    p0End: { hand: [] },
    gain: { monsters: ["Mimighoul Fairy"] },
  },
  {
    code: 82933935, name: "Mimighoul Flower", slug: "mimighoul-flower", does: "Special Summons itself from the hand face-down in Defense Position",
    p0: { hand: ["Mimighoul Flower"] },
    opp: {},
    partner: {},
    steps: [activate("Mimighoul Flower", "p0")],
    p0End: { hand: [] },
    gain: { monsters: ["Mimighoul Flower"] },
  },
  {
    code: 81522098, name: "Mimighoul Dragon", slug: "mimighoul-dragon", does: "Special Summons itself from the hand face-down in Defense Position",
    p0: { hand: ["Mimighoul Dragon"] },
    opp: {},
    partner: {},
    steps: [activate("Mimighoul Dragon", "p0")],
    p0End: { hand: [] },
    gain: { monsters: ["Mimighoul Dragon"] },
  },
  {
    code: 23920796, name: "Mimighoul Cerberus", slug: "mimighoul-cerberus", does: "Special Summons itself from the hand face-down in Defense Position",
    p0: { hand: ["Mimighoul Cerberus"] },
    opp: {},
    partner: {},
    steps: [activate("Mimighoul Cerberus", "p0")],
    p0End: { hand: [] },
    gain: { monsters: ["Mimighoul Cerberus"] },
  },
  {
    code: 50415441, name: "Mimighoul Archfiend", slug: "mimighoul-archfiend", does: "Special Summons itself from the hand face-down in Defense Position",
    p0: { hand: ["Mimighoul Archfiend"] },
    opp: {},
    partner: {},
    steps: [activate("Mimighoul Archfiend", "p0")],
    p0End: { hand: [] },
    gain: { monsters: ["Mimighoul Archfiend"] },
  },  {
    code: 22404675, name: "Mithra the Thunder Vassal", slug: "mithra-the-thunder-vassal", does: "Special Summons a Vassal Token in Defense Position",
    p0: { hand: ["Mithra the Thunder Vassal"] },
    steps: [activate("Mithra the Thunder Vassal", "p0")],
    p0End: { monsters: ["Mithra the Thunder Vassal"], hand: [] },
    gain: { tokens: { count: 1 } },
  },
  {
    code: 22411609, name: "Volcanic Trooper", slug: "volcanic-trooper", does: "Special Summons a Bomb Token",
    p0: { hand: ["Giant Rat"], monsters: ["Volcanic Trooper"] },
    steps: [activate("Volcanic Trooper", "p0")],
    p0End: { monsters: ["Volcanic Trooper"], hand: [], grave: ["Giant Rat"] },
    gain: { tokens: { count: 1 } },
  },
  {
    code: 25131968, name: "Ken the Warrior Dragon", slug: "ken-the-warrior-dragon", does: "Special Summons Gen the Diamond Tiger from the deck in Defense Position",
    p0: { monsters: ["Ken the Warrior Dragon"], deck: ["Gen the Diamond Tiger"] },
    steps: [activate("Ken the Warrior Dragon", "p0")],
    p0End: { monsters: ["Ken the Warrior Dragon"] },
    gain: { monsters: ["Gen the Diamond Tiger"] },
  },
  {
    code: 52126602, name: "Gen the Diamond Tiger", slug: "gen-the-diamond-tiger", does: "Special Summons Ken the Warrior Dragon from the deck in Defense Position",
    p0: { monsters: ["Gen the Diamond Tiger"], deck: ["Ken the Warrior Dragon"] },
    steps: [activate("Gen the Diamond Tiger", "p0")],
    then: [select("Mystical Elf")],
    p0End: { monsters: ["Gen the Diamond Tiger"], hand: ["Mystical Elf"], grave: ["Mystical Elf"] },
    gain: { monsters: ["Ken the Warrior Dragon"] },
  },  {
    code: 54191698, name: "Number 29: Mannequin Cat", slug: "number-29-mannequin-cat", does: "Special Summons a monster of an opponent Graveyard",
    p0: { monsters: [{ card: "Number 29: Mannequin Cat", materials: [ELF, ELF] }] },
    tgt: { monsters: [ELF], grave: [MAGICIAN] },
    steps: [activate("Number 29: Mannequin Cat", "p0")],
    then: [select(ELF), no("p0")],
    p0End: { monsters: ["Number 29: Mannequin Cat"], grave: ["Mystical Elf"] },
    tgtEnd: { monsters: [ELF, MAGICIAN] },
  },
  {
    code: 44689688, name: "Jurrac Spinos", slug: "jurrac-spinos", does: "Special Summons a Jurrac Token when it destroys a monster by battle",
    attackFirstTurn: true,
    noPick: true,
    p0: { monsters: ["Jurrac Spinos"] },
    tgt: { monsters: [{ card: "Kuriboh", pos: "def" }] },
    steps: (roles) => [attack("Jurrac Spinos", { card: "Kuriboh", owner: roles.tgt }, "p0")],
    p0End: { monsters: ["Jurrac Spinos"] },
    tgtEnd: { grave: ["Kuriboh"], tokens: { count: 1 } },
  },
  {
    code: 48228390, name: "Pyrite Knight", slug: "pyrite-knight", does: "Special Summons a Pyrite Token",
    p0: { hand: ["Pyrite Knight"], monsters: ["Gaia The Fierce Knight"] },
    steps: [activate("Pyrite Knight", "p0")],
    p0End: { hand: ["Gaia The Fierce Knight"], monsters: ["Pyrite Knight"] },
    gain: { tokens: { count: 1 } },
  },
  {
    code: 41141943, name: "Superheavy Samurai Transporter", slug: "superheavy-samurai-transporter", does: "Special Summons a monster from the hand of its controller in Defense Position",
    p0: { monsters: ["Superheavy Samurai Transporter"], hand: ["Giant Rat"] },
    steps: [activate("Superheavy Samurai Transporter", "p0")],
    p0End: { hand: ["Mystical Elf"], grave: ["Superheavy Samurai Transporter"] },
    gain: { monsters: ["Giant Rat"] },
  },
  {
    code: 26964762, name: "Destiny HERO - Dark Angel", slug: "destiny-hero-dark-angel", does: "Special Summons a Destiny HERO from the own Graveyard in Defense Position",
    p0: { hand: ["Destiny HERO - Dark Angel"], grave: ["Destiny HERO - Malicious", "Destiny HERO - Diamond Dude", "Destiny HERO - Denier"] },
    steps: [activate("Destiny HERO - Dark Angel", "p0")],
    then: [select("Destiny HERO - Malicious")],
    p0End: { hand: [], grave: ["Destiny HERO - Diamond Dude", "Destiny HERO - Denier", "Destiny HERO - Dark Angel"] },
    gain: { monsters: ["Destiny HERO - Malicious"] },
  },
  {
    code: 39829561, name: "Destiny HERO - Departed", slug: "destiny-hero-departed", does: "Special Summons itself from the Graveyard in the Standby Phase of its owner",
    p0: { grave: ["Destiny HERO - Departed"] },
    steps: [],
    p0End: { grave: [] },
    gain: { monsters: ["Destiny HERO - Departed"] },
  },
];

export const MONSTER_EFFECT_SCENARIOS = SPECS.flatMap(effectScenarios);
