import { activate, endTurn, expectBoard, select, specialSummon, type BoardExpect, type DuelistId, type Scenario, type Step } from "../../support/dsl.js";
import { defineScenarioWithFfaFirstDraw as defineScenario } from "./ffa-first-draw.js";
import { SOURCE } from "./nseat-scenarios.js";
type Format="ffa3"|"ffa4"|"tag"; const seat=(i:number)=>`p${i}` as DuelistId;
const CARDS=[[2139640,"Amabie"],[32835363,"Cracking"],[38522377,"Meklord Astro Dragon Asterisk"],[89405199,"Greed"],[93671934,"Morale Boost"]] as const;
function probe(format:Format,actor:0|1,[code,card]:typeof CARDS[number]):Scenario{
 const n=format==="ffa3"?3:4,late=format==="tag"?(actor===0?3:2):n-1,other=actor===0?1:0;
 const setup:Scenario["setup"]={format},board:BoardExpect={},steps:Step[]=[];
 for(let i=0;i<n;i++){const hand=format==="tag"&&i>=2?["Silver Fang"]:[];setup[seat(i)]={hand:[...hand]};board[seat(i)]={lp:format==="tag"?16000:8000,hand:[...hand],monsters:[],spells:[],grave:[],banished:[]};}
 const add=(target:number,amount:number)=>{for(let i=0;i<n;i++)if(i===target||(format==="tag"&&i%2===target%2))board[seat(i)]!.lp!+=amount;};
 if(code===2139640){setup[seat(actor)]!.hand=[card];if(actor===1){steps.push(endTurn("p0"));(board.p1!.hand as string[]).push("Mystical Elf");}steps.push(activate(card,seat(actor)));(board[seat(actor)]!.hand as string[]).unshift(card);for(let i=0;i<n;i++)board[seat(i)]!.lp!+=format==="tag"?600:300;
 }else if(code===32835363){setup[seat(actor)]!.spells=[card];setup[seat(actor)]!.hand=["Dark Hole"];board[seat(actor)]!.spells=[card];for(let i=0;i<n;i++){setup[seat(i)]!.monsters=["Beaver Warrior"];board[seat(i)]!.grave=["Beaver Warrior"];board[seat(i)]!.lp!-=800;}if(actor===1){steps.push(endTurn("p0"));(board.p1!.hand as string[]).push("Mystical Elf");}steps.push(activate("Dark Hole",seat(actor)));(board[seat(actor)]!.grave as string[]).push("Dark Hole");
 }else if(code===38522377){setup[seat(actor)]!.monsters=[card,"Jet Synchron","Beaver Warrior"];setup[seat(actor)]!.extra=["Ally of Justice Catastor"];if(actor===1){steps.push(endTurn("p0"));(board.p1!.hand as string[]).push("Mystical Elf");}steps.push(specialSummon("Ally of Justice Catastor",seat(actor)),select("Jet Synchron","Beaver Warrior"));board[seat(actor)]!.monsters=[card,"Ally of Justice Catastor"];board[seat(actor)]!.grave=["Jet Synchron","Beaver Warrior"];add(actor,-1000);
 }else if(code===89405199){setup[seat(actor)]!.spells=[card];setup[seat(actor)]!.hand=["Pot of Greed"];board[seat(actor)]!.spells=[card];if(actor===1){steps.push(endTurn("p0"));(board.p1!.hand as string[]).push("Mystical Elf");}steps.push(activate("Pot of Greed",seat(actor)),endTurn(seat(actor)));(board[seat(actor)]!.hand as string[]).push("Mystical Elf","Mystical Elf");(board[seat((actor+1)%n)]!.hand as string[]).push("Mystical Elf");board[seat(actor)]!.grave=["Pot of Greed"];add(actor,-1000);
 }else{setup[seat(actor)]!.spells=[card];setup[seat(actor)]!.hand=["Axe of Despair","Dark Hole"];setup[seat(late)]!.monsters=["Luster Dragon"];setup[seat(other)]!.monsters=["Beaver Warrior"];board[seat(actor)]!.spells=[card];if(actor===1){steps.push(endTurn("p0"));(board.p1!.hand as string[]).push("Mystical Elf");}steps.push(activate("Axe of Despair",seat(actor)),select({card:"Luster Dragon",owner:seat(late)}));board[seat(actor)]!.spells=[card,"Axe of Despair"];board[seat(actor)]!.hand=[...(board[seat(actor)]!.hand as string[]),"Dark Hole"];board[seat(late)]!.monsters=["Luster Dragon"];board[seat(other)]!.monsters=["Beaver Warrior"];add(actor,1000);steps.push(expectBoard(structuredClone(board)),activate("Dark Hole",seat(actor)));board[seat(actor)]!.spells=[card];board[seat(actor)]!.hand=(board[seat(actor)]!.hand as string[]).filter(x=>x!=="Dark Hole");board[seat(actor)]!.grave=["Axe of Despair","Dark Hole"];board[seat(late)]!.monsters=[];board[seat(other)]!.monsters=[];board[seat(late)]!.grave=["Luster Dragon"];board[seat(other)]!.grave=["Beaver Warrior"];add(actor,-1000);
 }
 steps.push(expectBoard(board));return defineScenario({id:`player-all-overlay-lp-${code}-${format}-p${actor}`,title:`${card}: LP follows each duelist or the real affected controller`,source:`${SOURCE} [Q3] [Q6]`,rules:["R-COMMON-EACH-PLAYER"],tags:["multiplayer","player-all-overlay-lp",format,`card:${code}`],setup,steps});
}
export const PLAYER_ALL_OVERLAY_LP_SCENARIOS=CARDS.flatMap(card=>([["ffa3",0],["ffa4",0],["tag",0],["tag",1]] as const).map(([format,actor])=>probe(format,actor,card)));
